logging:
  level:
    org.springframework.security: INFO
spring:
  profiles:
    active: test
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: twsny-stardardclient
            client-secret: sdzJsaOs4vvJHHJVYvRhGJO5urd4QTlq
            scope: openid,profile,email
            provider: keycloak-auth
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            # 新版本不兼容采用下面的方式
            issuer-uri: https://demo.jousing.cn:8090/realms/twsny-stardardrealm
server:
  port: 8080