logging:
  level:
    org.springframework.security: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          twsny-auth:
            client-id: twsny-client
            client-secret: 123456
            scope: openid,profile,email
            provider: twsny-auth
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          keycloak-auth:
            client-id: twsny-stardardclient
            client-secret: sdzJsaOs4vvJHHJVYvRhGJO5urd4QTlq
            scope: openid,profile,email
            provider: keycloak-auth
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          keycloak-github-auth:
            client-id: twsny-githubclient
            client-secret: MxwKypFVbrOuepXk5msyiFU3caHUjrTq
            scope: openid,profile,email
            provider: keycloak-github-auth
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          twsny-auth:
            issuer-uri: http://127.0.0.1:9000
          keycloak-auth:
            issuer-uri: https://demo.jousing.cn:8090/realms/twsny-stardardrealm
          keycloak-github-auth:
            issuer-uri: https://demo.jousing.cn:8090/realms/twsny-githubrealm
#          keycloak-custom-auth:
#            issuer-uri: https://demo.jousing.cn:8090/realms/twsny-customrealm

server:
  port: 8081
  servlet:
    session:
      cookie:
        # 本地 http 环境，Lax 最稳妥（从 9000 跳回 8081 仍会发送）
        same-site: LAX
        # 如果你显式开启了 none，请一定配 secure=true（https）
#        domain: localhostClient
#        same-site: NONE
#        secure: false
twsny:
  login:
    callback:
      path: http://localhost:5173/loginback