logging:
  level:
    org.springframework.security: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          twsny:
            client-id: twsny-client
            client-secret: 123456
            scope: openid,profile,email
            provider: twsny
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          twsny:
            issuer-uri: http://127.0.0.1:9000
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            user-info-uri: http://localhost:9000/userinfo
#            jwk-set-uri: http://localhost:9000/oauth2/jwks
#            user-name-attribute: sub

server:
  port: 8081
  servlet:
    session:
      cookie:
        # 本地 http 环境，Lax 最稳妥（从 9000 跳回 8081 仍会发送）
        same-site: LAX
        # 如果你显式开启了 none，请一定配 secure=true（https）
#        domain: localhostClient
#        same-site: NONE
#        secure: false
twsny:
  login:
    callback:
      path: http://localhost:5173/loginback