logging:
  level:
    org.springframework.security: INFO
spring:
  profiles:
    active: test
  security:
    oauth2:
      client:
        registration:
#        github:
#          client-id: Ov23liWRkr7Gz4MRhmEV
#          client-secret: 6e2da9ace4c553493946fe160980d7a1b26a0ab3
#        google:
#          client-id: 999109956096-57lq5gkpltp8saktd2lad3im0r0uknbr.apps.googleusercontent.com
#          client-secret: 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
          keycloak-auth:
            client-id: twsny-stardardclient
            client-secret: sdzJsaOs4vvJHHJVYvRhGJO5urd4QTlq
            scope: openid,profile,email
            provider: keycloak-auth
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak-auth:
            # 新版本不兼容采用下面的方式
            issuer-uri: https://demo.jousing.cn:8090/realms/twsny-stardardrealm
server:
  port: 8080