spring:
  security:
    oauth2:
      client:
        registration:
          github:
            # testAppForOAuth2.0_20250731
            client-id: Ov23liWRkr7Gz4MRhmEV
            client-secret: 6e2da9ace4c553493946fe160980d7a1b26a0ab3
            # testAppForOAuth2.0_20250801
#            client-id: Ov23liJIyZ1RGy1rr6a4
#            client-secret: e7c60a8281a4650fc3295699ffd9a8038a5d1dba
server:
  port: 8080