spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liWRkr7Gz4MRhmEV
            client-secret: 6e2da9ace4c553493946fe160980d7a1b26a0ab3

#logging:
#  level:
#    org.springframework.security: DEBUG
server:
  port: 8080
