logging:
  level:
    org.springframework.security: INFO
spring:
  profiles:
    active: test
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: testClient20250803
            client-secret: 0Xj95G0tw4WodNQDLjX07GaksA4euOqm
            scope: openid,profile,email
            provider: keycloak
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            # 新版本不兼容采用下面的方式
            issuer-uri: https://demo.jousing.cn:8090/realms/testRealm20250803
server:
  port: 8080